---
title: "Capacity Building Activities Report"
author: "EAR Team"
date: "June 28, 2015"
output: pdf_document
classoption: portrait
---


```{r, echo=FALSE}
###############################################################################
## To do:
## - Change country boundaries to be FAO compliant using the FAOSTAT package.
## - Wrap some of the table text, when necessary
## - Get some real data!
## - Add some more plots/tables based on management interest

##Get working directory 
if(Sys.info()[7] == "rockc_000"){ # Josh personal
  setwd("~/GitHub/EAR/")
} else if(Sys.info()[7] == "josh"){ # Josh work
  setwd("~/Documents/Github/EAR/")
} else if(Sys.info()[5] == "x86_64"){
  setwd("~/Dropbox/ad_hoc_R/EAR")  #Mac
} else {
  setwd("C:/Users/rahija/Dropbox/ad_hoc_R/EAR") #FAO
}

# library(devtools)
# install.packages("cellranger")
# install_github(repo = "jennybc/googlesheets")

suppressMessages({
library(ggplot2)
library(maps)
library(dplyr)
library(scales)
source('retrieveGoogle.R')
})
```

A quick summary of the capacity development activities:

```{r, echo=FALSE}
suppressMessages({
capDev <- retrieveGoogle(wbtitle = c("Capacity Building database - Team X",
                                     "Capacity Building database - Team Y"),
                         reportype = "Capacity Building")
})

knitr::kable(capDev[, c("Project", "Country", "Status", "Team")],
             caption = "Capacity Development Overview", align = "l") 
```

Here's a summary of the capacity development activities by country:

```{r, echo=FALSE}
summTab = capDev %>%
    group_by(Country) %>%
    dplyr::summarize(Budget = sum(as.numeric(as.character(Budget))),
                     Activities = n())
knitr::kable(summTab, caption = "Capacity Development by Country", align = "l")
```

```{r, echo=FALSE, fig.cap='Budget by Country'}
suppressMessages({ suppressWarnings({
mapData <- map_data(map = "world")
summTab <- capDev %>%
    group_by(Country) %>%
    dplyr::summarize(Budget = sum(as.numeric(as.character(Budget))),
                     Activities = n())
summTab$region <- summTab$Country
mapData <- left_join(mapData, summTab, by = "region")
})})
qplot(long, lat, fill = Budget, data = mapData, group = group,
      geom ="polygon", ylab="", xlab="") +
    scale_fill_continuous(label = dollar)
```

```{r, echo=FALSE, fig.cap='Activities by Country'}
qplot(long, lat, fill = Activities, data = mapData, group = group,
      geom ="polygon", ylab="", xlab="")
```

\newpage

A quick summary of the available code/algorithms:

```{r, echo=FALSE}
suppressMessages({
codeRep <- retrieveGoogle(wbtitle = c("Capacity Building database - Team X",
                                      "Capacity Building database - Team Y"),
                          reportype = "Code Repo")
})
knitr::kable(codeRep[, c("Algorithm_Title", "Language", "Department", "Team")],
                       caption = "Code Repository Overview", align = "l") 
```

Here's a summary of the programming languages used by team:

```{r, echo=FALSE}
summTab <- table(codeRep[, c("Language", "Team")])
knitr::kable(summTab, caption = "Summary by Language", align = "l")
ggplot(codeRep, aes(x = Team, fill = Language)) +
    geom_bar() + labs(y = "Algorithm Count")
```